/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SubscriptionRouteImport } from './pages/subscription'
import { Route as SettingsRouteImport } from './pages/settings'
import { Route as RegisterRouteImport } from './pages/register'
import { Route as PromotionsRouteImport } from './pages/promotions'
import { Route as LoginRouteImport } from './pages/login'
import { Route as FavoritesRouteImport } from './pages/favorites'
import { Route as IndexRouteImport } from './pages/index'
import { Route as PromotionsNewRouteImport } from './pages/promotions.new'
import { Route as ProfileUserIdRouteImport } from './pages/profile.$userId'
import { Route as ProductsProductIdRouteImport } from './pages/products.$productId'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsNewRoute = PromotionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PromotionsRoute,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/promotions': typeof PromotionsRouteWithChildren
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/promotions/new': typeof PromotionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/promotions': typeof PromotionsRouteWithChildren
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/promotions/new': typeof PromotionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/promotions': typeof PromotionsRouteWithChildren
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/promotions/new': typeof PromotionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/login'
    | '/promotions'
    | '/register'
    | '/settings'
    | '/subscription'
    | '/products/$productId'
    | '/profile/$userId'
    | '/promotions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/login'
    | '/promotions'
    | '/register'
    | '/settings'
    | '/subscription'
    | '/products/$productId'
    | '/profile/$userId'
    | '/promotions/new'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/login'
    | '/promotions'
    | '/register'
    | '/settings'
    | '/subscription'
    | '/products/$productId'
    | '/profile/$userId'
    | '/promotions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  PromotionsRoute: typeof PromotionsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionRoute: typeof SubscriptionRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions/new': {
      id: '/promotions/new'
      path: '/new'
      fullPath: '/promotions/new'
      preLoaderRoute: typeof PromotionsNewRouteImport
      parentRoute: typeof PromotionsRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PromotionsRouteChildren {
  PromotionsNewRoute: typeof PromotionsNewRoute
}

const PromotionsRouteChildren: PromotionsRouteChildren = {
  PromotionsNewRoute: PromotionsNewRoute,
}

const PromotionsRouteWithChildren = PromotionsRoute._addFileChildren(
  PromotionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  PromotionsRoute: PromotionsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionRoute: SubscriptionRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
